"""init

Revision ID: 127c8c0124ee
Revises:
Create Date: 2023-03-06 17:57:12.695638

"""
import sqlalchemy as sa
from alembic import op
from database import Base


# revision identifiers, used by Alembic.
revision = "127c8c0124ee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
