"""second migration

Revision ID: 26226e8da6cb
Revises: 127c8c0124ee
Create Date: 2023-03-06 18:14:36.480034

"""
import sqlalchemy as sa
from alembic import op
from database import Base


# revision identifiers, used by Alembic.
revision = "26226e8da6cb"
down_revision = "127c8c0124ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
