"""init

Revision ID: 62e3457faeaf
Revises:
Create Date: 2023-03-06 21:50:26.862773

"""
import sqlalchemy as sa
from alembic import op
from database import Base


# revision identifiers, used by Alembic.
revision = "62e3457faeaf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tnamescounter",
        sa.Column("idcounter", sa.Integer(), nullable=False),
        sa.Column("namecounter", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("nohp", sa.String(), nullable=False),
        sa.Column("otp", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("timeclosing", sa.Time(), nullable=True),
        sa.PrimaryKeyConstraint("idcounter"),
        sa.UniqueConstraint("nohp"),
    )
    op.create_table(
        "ttransaksiqueue",
        sa.Column("idqueue", sa.Integer(), nullable=False),
        sa.Column("idcounter", sa.Integer(), nullable=True),
        sa.Column("nohpclient", sa.String(), nullable=False),
        sa.Column("statusclient", sa.String(length=20), nullable=True),
        sa.Column("statusnumber", sa.String(length=20), nullable=True),
        sa.Column("yournumber", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["idcounter"],
            ["tnamescounter.idcounter"],
        ),
        sa.PrimaryKeyConstraint("idqueue"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ttransaksiqueue")
    op.drop_table("tnamescounter")
    # ### end Alembic commands ###
